[AutoRun]
enabled=false
program=

[BitTorrent]
Session\DefaultSavePath=/download/Qdown
Session\TempPath=/download/inQdown
Session\Port=8999
Session\MaxConnections=500
Session\MaxConnectionsPerTorrent=100
Session\MaxUploads=-1
Session\MaxUploadsPerTorrent=-1

[Core]
AutoDeleteAddedTorrentFile=Never

[GUI]
StartUpWindowState=Normal

[LegalNotice]
Accepted=true

[Network]
Proxy\OnlyForTorrents=false

[Preferences]
Connection\UPnP=true
Downloads\SavePath=/download/Qdown
Downloads\TempPath=/download/inQdown
Downloads\ScanDirsV2=@Invalid()
General\Locale=zh
MailNotification\enabled=false
WebUI\Port=8080
WebUI\LocalHostAuth=true
WebUI\AuthSubnetWhitelist=127.0.0.1/32
WebUI\AuthSubnetWhitelistEnabled=true
